### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by DmitryKrekota**
When I tried to run tests with benderjs, I received an error:
_Potentially unhandled rejection [1] TypeError: Cannot read property 'prototype' of undefined_
bender
To fix this problem I put the latest version of socket.io to /node_modules/benderjs/node_modules/ instead of old socket.io.
So, I offer to update dependencies in your project.

### CODE REVIEW

**Comment by mlewand** [comment]
Thanks @DmitryKrekota. Sorry for taking it so long for us to review this change, but we had very little time to check for Bender (as seen above).

Let's get it reviewed.

**Comment by msamsel** [comment]
Hi @DmitryKrekota,
thank you for your pull request.
Unfortunately your pull request update too much packages, what cause other errors e.g. `broadway`. Based on this case I was able to prepare another solution with smaller update, which is working. :) You can find my pull here: #256.
It should work with newer nodejs version and fix mentioned error.
We're going to introduce changes to master branch in near future. You'll be update when this happen.

**Comment by DmitryKrekota** [comment]
@msamsel, ok, I do not mind and I will wait for marging #256 PR.

**Comment by mlewand** [comment]
Mentioned #256 fixes support for node 7.x without breaking broadway. Thanks for the contribution!

**Pull request closed without merging**
